In [16]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn import cross_validation
import csv

In [17]:
test = pd.read_csv('C:\\Users\\User\\Downloads\\ad_org_test.csv',sep='\s*,\s*', skipinitialspace=True, engine='python')

In [18]:
train = pd.read_csv('C:\\Users\\User\\Downloads\\ad_org_train.csv',sep='\s*,\s*', skipinitialspace=True, engine='python')

In [19]:
train.head(5)

,vidid,adview,views,likes,dislikes,comment,published,duration,category
0,VID_18655,40,1031602,8523,363,1095,2016-09-14,PT7M37S,F
1,VID_14135,2,1707,56,2,6,2016-10-01,PT9M30S,D
2,VID_2187,1,2023,25,0,2,2016-07-02,PT2M16S,C
3,VID_23096,6,620860,777,161,153,2016-07-27,PT4M22S,H
4,VID_10175,1,666,1,0,0,2016-06-29,PT31S,D

In [20]:
train.dtypes
l=[]
for i in train['duration']:
    a = i.lstrip('PT').rstrip('S').replace('H','.').replace('M','.').split('.')
    try:
        if len(a)==3:
            time = int(a[0])*60*60 + int(a[1])*60 + int(a[2])
        elif len(a)==2:
            time = int(a[0])*60 + int(a[1])
        else:
            time = int(a[0])
    except:
        time = int(a[0])*60
    l.append(time)
train['duration'] = l

In [21]:
def to_xy(df, target):
    result = []
    for x in df.columns:
        if x != target:
            result.append(x)
  
    target_type = df[target].dtypes
    target_type = target_type[0] if hasattr(target_type, '__iter__') else target_type
   
    return df.as_matrix(result).astype(np.float32), df.as_matrix([target]).astype(np.float32)

In [22]:
l =[]
for i in train['views']:
    try :
        l.append(int(i))
    except:
        l.append(0)
train['views'] = l

In [23]:
l =[]
for i in train['adview']:
    try :
        l.append(int(i))
    except:
        l.append(0)
train['adview'] = l

In [24]:
l =[]
for i in train['likes']:
    try :
        l.append(int(i))
    except:
        l.append(0)
train['likes'] = l

In [25]:
l =[]
for i in train['dislikes']:
    try :
        l.append(int(i))
    except:
        l.append(0)
train['dislikes'] = l

In [26]:
l =[]
for i in train['comment']:
    try :
        l.append(int(i))
    except:
        l.append(0)
train['comment'] = l
l =[]
for i in train['category']:
    try :
        l.append(int(i))
    except:
        l.append(0)
train['category'] = l

In [27]:
l =[]
for i in train['published']:
    try :
        l.append(int(i[:4]))
    except:
        l.append(0)
train['year'] = l
l =[]
for i in train['published']:
    try :
        l.append(int(i[5:7]))
    except:
        l.append(0)
train['month'] = l
train.drop('published',axis=1,inplace=True)

In [28]:
train
train['category'].value_counts()
train['category'] = train['views']/train['duration']
train

,vidid,adview,views,likes,dislikes,comment,duration,category,year,month
0,VID_18655,40,1031602,8523,363,1095,457,2257.334792,2016,9
1,VID_14135,2,1707,56,2,6,570,2.994737,2016,10
2,VID_2187,1,2023,25,0,2,136,14.875000,2016,7
3,VID_23096,6,620860,777,161,153,262,2369.694656,2016,7
4,VID_10175,1,666,1,0,0,31,21.483871,2016,6
5,VID_10756,4,78,0,0,0,15,5.200000,2016,5
6,VID_9782,40621,43118,15,1,0,200,215.590000,2015,8
7,VID_16452,1,14205,55,16,1,58,244.913793,2016,8
8,VID_18486,1,526015,3064,211,2582,1670,314.979042,2015,11
9,VID_681,1,406992,3831,310,7839,679,599.399116,2016,10
10,VID_10116,19,607447,377,144,65,745,815.365101,2016,8
11,VID_1763,9,429137,2181,76,172,228,1882.179825,2015,12
12,VID_1979,224,1895,59,5,0,254,7.460630,2016,8
13,VID_9313,1,59843,68,16,10,8608,6.952021,2016,2
14,VID_18397,2,211642,1378,65,103,170,1244.952941,2015,4
15,VID_1025,1,3700,29,6,3,37,100.000000,2013,9
16,VID_19903,2,2303,4,0,0,26,88.576923,2010,10
17,VID_10866,4794,5886,23,0,4,312,18.865385,2016,11
18,VID_22884,107,9477,66,0,0,22,430.772727,2015,6
19,VID_22583,53702,115426,83,10,2,196,588.908163,2015,9
20,VID_11702,2,62255,71,10,1,761,81.806833,2015,6
21,VID_8074,1,15353,13,6,9,101,152.009901,2016,8
22,VID_11952,1,236589,1730,38,140,325,727.966154,2015,8
23,VID_8520,2,94719,192,11,23,41,2310.219512,2016,8
24,VID_13368,14,3089826,7493,1148,330,798,3871.962406,2016,4
25,VID_19981,3,2046444,3910,845,247,362,5653.160221,2015,12
26,VID_1123,3,2103487,13342,734,650,659,3191.937785,2014,8
27,VID_5128,3,740683,935,68,57,98,7557.989796,2013,9
28,VID_1403,1,805979,2036,183,215,131,6152.511450,2015,3
29,VID_11724,1,229495,372,50,44,8552,26.835243,2014,5
...,...,...,...,...,...,...,...,...,...,...
14969,VID_5709,1,1076056,958,166,55,275,3912.930909,2013,11
14970,VID_6100,2,255555,621,54,45,310,824.370968,2015,3
14971,VID_21972,1,34447,54,6,6,2004,17.189122,2015,8
14972,VID_14395,1,191080,175,27,12,207,923.091787,2014,2
14973,VID_8673,10,1266,1,0,0,11,115.090909,2016,3
14974,VID_3735,5,1406764,695,189,62,302,4658.158940,2014,8
14975,VID_3230,7,481215,382,150,34,2595,185.439306,2014,2
14976,VID_2132,1,12934,30,2,0,153,84.535948,2016,7
14977,VID_13740,4,10716,0,0,0,138,77.652174,2016,9
14978,VID_4424,1,216284,486,29,17,229,944.471616,2014,4
14979,VID_1314,272,1520441,18677,367,3971,508,2992.994094,2016,5
14980,VID_14670,231,1532,266,24,5,309,4.957929,2016,2
14981,VID_7541,1,168226,184,27,29,133,1264.857143,2014,3
14982,VID_4956,1,45964,36,5,2,162,283.728395,2014,12
14983,VID_7956,12,180204,361,17,20,74,2435.189189,2013,7
14984,VID_13145,1,1511,6,1,0,87,17.367816,2014,1
14985,VID_566,1,32631,76,4,14,804,40.585821,2014,1
14986,VID_17470,3207,22237,52,4,14,318,69.927673,2016,9
14987,VID_18084,1,303879,481,51,76,137,2218.094891,2014,6
14988,VID_22836,2,214596,1431,44,67,212,1012.245283,2015,8
14989,VID_20638,22,1204587,10284,379,2016,619,1946.021002,2013,4
14990,VID_11386,15,525829,350,222,0,1778,295.741845,2016,7
14991,VID_2502,1,333336,152,84,0,1120,297.621429,2015,12
14992,VID_11653,1,78021,422,19,14,177,440.796610,2016,8
14993,VID_13909,11,96816,122,9,11,126,768.380952,2014,1
14994,VID_31,2,525949,1137,83,86,370,1421.483784,2015,5
14995,VID_5861,1,665673,3849,156,569,236,2820.648305,2015,10
14996,VID_805,4,3479,16,1,1,193,18.025907,2013,8
14997,VID_19843,1,963,0,0,0,26,37.038462,2010,10
14998,VID_8534,1,15212,22,5,4,61,249.377049,2016,2

In [29]:
l =[]
for i in test['views']:
    try :
        l.append(int(i))
    except:
        l.append(0)
test['views'] = l
l =[]
for i in test['likes']:
    try :
        l.append(int(i))
    except:
        l.append(0)
test['likes'] = l
l =[]
for i in test['dislikes']:
    try :
        l.append(int(i))
    except:
        l.append(0)
test['dislikes'] = l
l =[]
for i in test['comment']:
    try :
        l.append(int(i))
    except:
        l.append(0)
test['comment'] = l
l=[]
for i in test['duration']:
    a = i.lstrip('PT').rstrip('S').replace('H','.').replace('M','.').split('.')
    try:
        if len(a)==3:
            time = int(a[0])*60*60 + int(a[1])*60 + int(a[2])
        elif len(a)==2:
            time = int(a[0])*60 + int(a[1])
        else:
            time = int(a[0])
    except:
        time = int(a[0])*60
    l.append(time)
test['duration'] = l
test['category'] = test['views']/test['duration']

In [30]:
X = train.drop(['vidid','adview'],axis=1)
y = train['adview']
from sklearn.ensemble import RandomForestRegressor
reg=RandomForestRegressor(n_estimators=200, max_depth=20,criterion='mse',n_jobs=-1,min_samples_leaf=3,min_samples_split=5)

In [15]:
reg.fit(X,y)

NameError: name 'reg' is not defined